version: 2
updates:
  - package-ecosystem: "npm" # Le gestionnaire de packages (npm, pip, cargo, etc.)
    directory: "/"           # Répertoire où se trouve le fichier package.json
    schedule:
      interval: "weekly"     # Fréquence de vérification (daily, weekly, monthly)
  - package-ecosystem: "npm" # Pour un projet Deno
    directory: "/"            # Répertoire contenant le fichier deno.json
    schedule:
      interval: "weekly"
